### ISSUE TITLE
street maps are breaking

### ISSUE THREAD

**Issue by bardiaurbn** [felixpalmer/procedural-gl-js#11]
for some reasons i can't use street maps, or basically anything except map-tiler satellite imagery

<img width="1343" alt="Screenshot 2020-12-18 at 10 47 08 PM" src="https://user-images.githubusercontent.com/69179329/102627468-3293cb80-4183-11eb-9332-8d20366a95f7.png">

**Comment by felixpalmer** [comment]
It certainly is possible to use street maps, after all the engine doesn't care, it is just raster imagery. My guess is that you are trying to load 512x512 tiles, but the engine needs 256x256 pixel tiles. Could you share what tile endpoint you are using?

**Comment by bardiaheshmati** [comment]
> It certainly is possible to use street maps, after all the engine doesn't care, it is just raster imagery. My guess is that you are trying to load 512x512 tiles, but the engine needs 256x256 pixel tiles. Could you share what tile endpoint you are using?

You're right i was importing 512x512 tiles.
Any plans to support 512 tiles later ?

**Comment by felixpalmer** [comment]
It's something I've been considering - there is more background here: https://github.com/felixpalmer/procedural-gl-js/issues/8
