### ISSUE TITLE
3D model, custom tiles and overlay

### ISSUE THREAD

**Issue by beshad** [felixpalmer/procedural-gl-js#18]
so glad to found this great repo, couple questions though: 

- can an image overlay be added over the map? also i can see only LineString but how about other types like circle etc? is there anything else can be added to the app in addition to markers and linestrings?
- being based on THREE JS, is it possible to load a 3D model?
- can i use custom local {z}{x}{y} imagery tiles?

cheers

**Comment by felixpalmer** [comment]
Glad you like it! To answer your questions:

- Adding an additional raster data source is planned for a future version and already tracked here: https://github.com/felixpalmer/procedural-gl-js/issues/3
- Not yet, but also planned for the future
- Yes, see this page for details: https://github.com/felixpalmer/procedural-gl-js/wiki/Data-sources
