### ISSUE TITLE
Custom Elevation Data API

### ISSUE THREAD

**Issue by chris-aeviator** [felixpalmer/procedural-gl-js#20]
Is it possible to let elevation data be independent of an external service? For example I can craft an API with openly available elevation data (see https://www.opentopodata.org/datasets/srtm/) but I don't see how to integrate such a self-hosted API.

**Comment by felixpalmer** [comment]
Currently the API does not expose this option, but I will add it soon. As a stopgap now I would recommend you use the integrated nasadem.XYZ tiles. 

Also in my experience, SRTM is worse than NASADEM so I wouldn't advise using it, but this is of course your choice. NASADEM is a cleaned up version of the SRTM dataset and is also openly available.

**Comment by chris-aeviator** [comment]
@felixpalmer thanks for your reply and the hint that NASADEM is available also for download. I was more looking into having the option to use arbitrary data rather than relying on a commercial external service. Looking forward to the update.

**Comment by felixpalmer** [comment]
@chris-aeviator I just pushed an update that allows arbitrary elevation data to be used, see https://github.com/felixpalmer/procedural-gl-js/wiki/Data-sources for details

**Comment by chris-aeviator** [comment]
:+1: 
awesome, thank you, will have a look. Btw. the github wiki is not rendering your HTML correctly.

**Comment by felixpalmer** [comment]
Not sure what is going on with the wiki, seems to be some bug with Github as sometimes it renders fine
