### ISSUE TITLE
Unexpected Behaviour after clicking on marker 

### ISSUE THREAD

**Issue by bardiaheshmati** [felixpalmer/procedural-gl-js#22]
**Description**
Camera makes a jump when clicking on markers if camera angle different from default.

**To Reproduce**
1. Go to [playground](https://felixpalmer.github.io/procedural-gl-js/docs/overlays.html)
2. Change camera's viewing angle
3. Click on any markers on the sidebar
4. Camera moves smoothly to the location then makes a sudden angle change

**Expected behavior**
Camera angle to change smoothly with the translate animation

**Screenshots**
[Example](https://s2.gifyu.com/images/ezgif.com-gif-maker22050a7fb09646fc.gif)

**Desktop**
 - OS: MacOS
 - Browser Safari, Chrome (88.0.4324.96)
 - Version 11.1

**Mobile**
 - OS: iOS
 - Browser Safari, Chrome
 - Version 14.3

**Comment by felixpalmer** [comment]
Thanks for this, I can verify that the jump is there. I will investigate

**Comment by bardiaheshmati** [comment]
you're a gem

**Comment by felixpalmer** [comment]
@bardiaheshmati this has been fixed in 1.0.16. Thanks for reporting!
