### ISSUE TITLE
Mapbox static tiles are not well placed

### ISSUE THREAD

**Issue by dotesfera** [felixpalmer/procedural-gl-js#25]
Hi, just tried to use mapbox static tile server, but it seems that some tile coordinates are messed, see here:

![Captura de ecrã 2021-03-04 190036](https://user-images.githubusercontent.com/30806279/110015577-ebe25600-7d1b-11eb-8196-c9f896f147eb.jpg)

Using this
```
const datasource = {
    elevation: {
      apiKey: APIKEY,
    },
    imagery: {
      apiKey: APIKEY,
      urlFormat: 'https://api.mapbox.com/styles/v1/mapbox/streets-v9/tiles/{z}/{x}/{y}?access_token={apiKey}',
  
  };
```

**Comment by felixpalmer** [comment]
As per the [documentation](https://github.com/felixpalmer/procedural-gl-js/wiki/Data-sources) the imagery tile size needs to be 256x256px. I looked at the Mapbox docs at https://docs.mapbox.com/api/maps/static-tiles/ and they state that the default tile size is 512px, thus you will need to change your URL to something like:

`urlFormat: 'https://api.mapbox.com/styles/v1/mapbox/streets-v9/tiles/256/{z}/{x}/{y}?access_token={apiKey}'`

**Comment by dotesfera** [comment]
Ok it worked. But this doubles the API requests in this mapbox case. Is there a way we can change the imagery tilesize to 516 for out case?
