### ISSUE TITLE
Calculate bounding box automatically with given markers array

### ISSUE THREAD

**Issue by dotesfera** [felixpalmer/procedural-gl-js#27]
Hi @felixpalmer , is it possible to center the map on a bounding box calculated automatically given the overlay markers?

**Comment by felixpalmer** [comment]
No, but you can focus on an area (bounds) using https://www.procedural.eu/module-Camera.html#.focusOnBounds

Calculating the bounds of a set of markers is pretty simple, you just take the minimum and maximum latitudes of all the markers (I'm sure there will also be libraries out there that do this).
