### ISSUE TITLE
[Question] is it possible to add an area (polygon) as an overlay?

### ISSUE THREAD

**Issue by tschoartschi** [felixpalmer/procedural-gl-js#34]
Hey!

Thanks for the great library. Really enjoyed trying it out so far 🙂 

I have one question:

Is it possible to add an area (polygon) as an overlay? I tried it now for some time but it does not seem to display. What I'm trying to achieve is something like this:

![image](https://user-images.githubusercontent.com/1695329/118172944-450dea80-b42d-11eb-916e-3a40446255f1.png)
https://geojson.io/#map=13/48.3135/14.3413

When I take the geojson and put it into the overlay editor: https://www.procedural.eu/overlays.html it seems that the area (polygon) is recognized correctly but I can not see anything. This is the geojson I tried:

```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "stroke": "#555555",
        "stroke-width": 2,
        "stroke-opacity": 1,
        "fill": "#ff0000",
        "fill-opacity": 0.5
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              14.361705780029295,
              48.318478372736365
            ],
            [
              14.34608459472656,
              48.308888618124726
            ],
            [
              14.359989166259767,
              48.29404377802783
            ],
            [
              14.386768341064451,
              48.2964420830209
            ],
            [
              14.38436508178711,
              48.314482860683626
            ],
            [
              14.361705780029295,
              48.318478372736365
            ]
          ]
        ]
      }
    }
  ]
}
```

Am I doing something wrong or is this feature not implemented right now?

Thanks a lot

**Comment by felixpalmer** [comment]
Polygons are not supported right now, however you can draw a polygon outline using a LineString though. It just won't be filled

**Comment by tschoartschi** [comment]
Thanks for the feedback 🙂 what you described is exactly what we did. We even took your idea one step further and filled the area with lot's of LineString 🙂 

But it's good to know that it's not supported so I do not need to search and browse the source code.

**Comment by felixpalmer** [comment]
🙂 glad you found a solution. Care to share what you're working on?

**Comment by tschoartschi** [comment]
I think we can share it but I need to align with @xxseabxx because he is the maintainer of the repo

**Comment by qbsho** [comment]
Hello @felixpalmer, 
we use your framework for a mountainbike singletrail map to highlight the potential in a small city in austria.
![image](https://user-images.githubusercontent.com/604580/120337870-fcdb3d00-c2f3-11eb-96d4-2e00f183e184.png)
First we played around with the local images but found out that the tiles from maptiler where better choice in performance and quality. The Information for the pins and the lines coming from gson and we enhance it with content in an api orchestration layer. we use vue.js v3 for the small tool.

I will add you as viewer to the project. I see a lot of potential in especially on mobile device in your lib. 
Thanks BR Sebastian
