### ISSUE TITLE
Offset location indicator line

### ISSUE THREAD

**Issue by ThomasHalwax** [felixpalmer/procedural-gl-js#37]
When using image markers I'm shifting them upwards to make them visible even if they would be clipped normally.
Additionally I draw a circle in order to mark the real position. With a growing number of images and/or a growing offset between the image marker and the real position users may not be able to assign image markers to the corresponding real positions.

I'd like to be able to draw an offset indicator line between the image marker an the real position. Please see the attached screenshot with a faked offset indicator line.

![image](https://user-images.githubusercontent.com/38359572/133615087-a819488a-30c8-4060-9052-d05c8691af00.png)

**Comment by felixpalmer** [comment]
Take a look at this example: https://www.procedural.eu/overlays.html#markers-examples/collapsing-pin
