### ISSUE TITLE
Mouse scroll zoom speed is slow

### ISSUE THREAD

**Issue by grandchild** [felixpalmer/procedural-gl-js#6]
When zooming with the mouse wheel, the zoom feels very slow.

Some values that I see in the JS debugger:
```JS
// handleMouseWheel():
event.deltaY = 3
getZoomScale(event.deltaY) = 0.999
scope.zoomSpeed = 0.5
```

This is the difference between what was probably 2 full mousewheel rotations, barely perceptable. (Excuse  the uneven cropping.)
![imgnote-042720fb-ffe8-40bf-8465-606d9a57a3ae](https://user-images.githubusercontent.com/770029/101523145-7ec35c80-3988-11eb-82b7-5f8a98b501a1.png)
![imgnote-ac664644-97fd-4a60-acba-a8ff5918cf7a](https://user-images.githubusercontent.com/770029/101523149-7ff48980-3988-11eb-8075-bd0e31e2eb05.png)

**Comment by felixpalmer** [comment]
Fixed in https://github.com/felixpalmer/procedural-gl-js/pull/9
