### ISSUE TITLE
Feature request: Support 512x512px imagery tiles

### ISSUE THREAD

**Issue by gorbypark** [felixpalmer/procedural-gl-js#8]
Most of the map tiles I use are in the "high dpi" 512x512px png format.  They currently load, but obviously look super weird as they are expected to be 256x256px.

**Comment by felixpalmer** [comment]
First note that loading 512x512 tiles will not increase the final render resolution. All it will do is make it harder for the engine to cover the landscape efficiently, you will likely end up downloading more data and the frame rate will drop.

The engine loads imagery into a 2048x2048 texture atlas. When the tiles are 256x256, we can fit 256 which gives good caching behavior and lets us cover the entire terrain without a problem. Raising to 512x512 means the atlas can only hold 16 tiles, which is nowhere near enough. It is possible to increase the atlas size (e.g. to 4096x4096) and thus support 256 512x512 tiles, however most mobile device cannot bind a texture larger than 2k.

As mobile support is top priority I don't want to expose changing the tile size, however if you really need it and are OK dropping mobile devices, you can change `IMAGERY_TILE_SIZE ` in `datasources/imagery.js`.

**Comment by gorbypark** [comment]
Thanks for the detailed response.

**Comment by tuukka** [comment]
There are two types of 512x512 map tiles: those intended for display on a high DPI screen (for smooth text and cartography) and those that are just four 256x256 tiles glued together for providing the same amount of pixels in a smaller number of files / HTTP requests. The latter type you can split into the smaller tiles on clients where 256x256 is optimal. Can't you always do this with imagery tiles to decouple the source format from the engine internals?

**Comment by felixpalmer** [comment]
Hmm, interesting idea. The engine could always download the large 512x512 and then just crop out the part needed. This would lead to more data being downloaded though, even if there might be a benefit in fewer network requests (and thus better download parallelism). But in the worst case it would 4X the data downloaded though. 

Is your use case here that you have an API that only supports 512x512 tiles or that you think it would improve the engine performance?
